//SESSION 2 - EXERCISES

/////////////////////////////////////////////////
//Put into practice all your sound synthesis tools in order to imitate certain sounds. Let's all approach the same list, so that we can share different approaches to the same sounds:

//1 - Tapping on wood with fingernails or/and tapping on glass with fingernails.
//2 - A very bad radio signal.
//3 - A water drop from a fauset.
//4 - A ventilation machine.
//5 - Oldschool rain.
